# Generated by Django 4.1.2 on 2022-10-26 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_body_post_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 15, 46, 34, 888294, tzinfo=datetime.timezone.utc), verbose_name='дата обращения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 15, 46, 34, 888294, tzinfo=datetime.timezone.utc), verbose_name='дата публикации'),
        ),
    ]
